init
hedonist88/java-explore-with-me pull request #1
Opened 2022-10-10 16:41 UTC by hedonist88

2022-10-14 12:28 UTC, Frilock requested changes
Добрый день, по работе, смотрите из основного:
1. Жду все таки от Вас живой сборки с тестами зелеными. Да были какие то изменения в них, но лучше уточнить у коллег. Работающие тесты я сегодня видел. Кроме того, на мой взгляд, на сервис слой нужно написать unit тесты. Автотесты это конечно хорошо, но свой код нужно самому тестить тоже, это хорошая практика.
2. Во многих местах исчезли модификаторы. Не понимаю, где то у Вас они есть, где то нет - нужно поправить.
3. Autowired лучше ставить над сеттером или конструктором. Проставлять на поле плохая практика
4. Во многих местах съехало форматирование, где то нет пробелом между методами, где то между другими конструкциями. Нужно поправить.
5. Не понял, почему таблицы называются с префиксом а. Зачем?
6. Не очень хорошая практика использовать совместно аннотации Data и Builder (скинул статью, посмотрите.)
7. Над полями классов модели нужно поставить аннотацию Column и указать в ней размерность полей, а также флаги, которые Вы указали в скриптах.
8. Предложил поставить плагин sonarlint - подскажет ряд хороших практик.

2022-10-14 12:28 UTC, Frilock commented on README.md
> +ExploreWithMe Java Practikim project
Смотрите, у Вас 15 коммитов, которые не имеют никакого четкого описания. Это плохо. Во первых, раз у них нет особо различий для Вас то сделайте из них один (выполнив rebase - заодно посмотрите как объединять коммиты). Ну и все таки нужно какое то вменяемое описание коммиту давать.
Во вторых, давайте в этот файлик добавим текстовое описание, за что отвечают Ваши модули. Так стороннему человеку который будет смотреть Ваш проект будет удобнее. Так же можно указать как проект запускается.

В третьих, все же я бы попросил починить сборку, я сегодня уже видел новые работы студентов, там тесты проходили, давайте дополнительное время потратим и попробуем их оживить.

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/resources/schema.sql
> +    app VARCHAR(100) NOT NULL,
Общий комментарий по скриптам и моделям:
1. Зачем вы добавляете в название таблицы a_...? Не очень понятно, на мой взгляд, не очень хорошая практика
2. Вот тут Вы указываете размерность полей это правильно, смотрите, теперь в классах модели давайте проставим над полями аннотацию  Column в которой укажем размерность полей и дополнительные флаги, например, nullable = false, что соответствует not null в скрипте. Это нужно для того, чтобы не лазить всегда в скрипты для просмотра размерности полей.

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/java/ru/practicum/explorewithme/hit/service/StatsServiceImpl.java
> +            for (Map.Entry<String, List<Hit>> entry:hitGroups.entrySet()) {
Съезжает форматирование, перед и после двоеточия нужен пробел. Пробегитесь по коду, проверьте другие места

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/java/ru/practicum/explorewithme/hit/repository/HitRepositoryCustomImpl.java
> +        if (start != null) {
По идее такой проверки недостаточно, может ведь прийти ""? Чтобы избежать таких проблем советую использовать Objects.isNotBlack(o1)

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/java/ru/practicum/explorewithme/hit/repository/HitRepository.java
> +@Repository
Над интерфейсом можно не ставить такую аннотацию, Спринг увидит наследование от JpaRepository сам

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/java/ru/practicum/explorewithme/hit/model/Hit.java
> +@Data
Использования одновременно Data и Builder не всегда хорошая идея https://habr.com/ru/company/haulmont/blog/564682/

2022-10-14 12:28 UTC, Frilock commented on ewm-statistics/src/main/java/ru/practicum/explorewithme/hit/mapper/HitMapper.java
> +                .timestamp(LocalDateTime.parse(hitDto.getTimestamp(), formatter))
hitDto.getTimestamp null не вернет? Там вроде метод parse not null параметр принимает.

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/service/UserValidator.java
> +    private UserRepository userRepository0;
Какая то адская штука, я так понял идея этой конструкции в том, чтобы сделать методы статическими? А стоит ли оно того?

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +    UserRepository userRepository;
Куда модификатор подевался?)

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements  UserService {
2 пробела вместо одного перед UserService =(

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/repository/UserRepository.java
> +@Repository
Над интерфейсами можно не ставить аннотации бинов для спринга, главное чтоб они стояли над реализациями

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/mapper/UserShortDto.java
> +    public String toString() {
Вроде такой же туСтринг сгенерирует ломбок

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/controller/AdminUserController.java
> +    @Autowired
Проставления аннотации Autowired над полем не очень хорошая практика. Нужно либо инжектить бины через конструктор либо через set метод. Давайте поправим этот момент.
Кроме того, не знаю, предлагали Вам или нет, но как вариант, можете себе в IDEA поставить плагин sonarlint - статический анализатор кода, подскажет ряд хороших практик

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/statistic/service/EventServiceAspect.java
> +    StatisticHitClient statisticHitClient;
Модификатор потерялся.

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/category/service/CategoryValidator.java
> +        if (name == null || name.isBlank()) {
Достаточно Objects.isBlank

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/event/controller/AdminEventController.java
> +@RestController
Строчку после импортов пропустите

2022-10-14 12:28 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/event/mapper/EventFullResponseDto.java
> +    Long id;
А куда модификаторы делись?)

2022-10-14 20:12 UTC, hedonist88 commented on README.md
> +ExploreWithMe Java Practikim project
15 комитов я тесты прогонял =) правки вносил, торопился, быстро все собрал, поэтому где то могу пропустить что-то(модификаторы), причешу код

2022-10-14 20:13 UTC, hedonist88 commented on ewm-statistics/src/main/resources/schema.sql
> +    app VARCHAR(100) NOT NULL,
a_ все справшивают) привычка с вэб разработки, префикс таблиц, иногда бывает полезно

2022-10-14 20:16 UTC, hedonist88 commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/service/UserValidator.java
> +    private UserRepository userRepository0;
Без этого в статику не запихать репозиторий, а некоторые проверки хотелось бы проверять прямо тут, в принципе нашел как решение, но можно конечно что-то написать в сервисе, но не хотелось бы

2022-10-14 21:18 UTC, hedonist88 commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/controller/AdminUserController.java
> +    @Autowired
Согласен, да, плохая практика, поторопился)

2022-10-19 18:22 UTC, Frilock requested changes
Добрый вечер, все в в целом поправили. Пара небольших комментариев. Прошу поменять пару проверок.

2022-10-19 18:22 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +            if (event.getState().equals(EventState.CANCELED)) {
Я Вам вроде писал что enum поля сравнивать через обычные операторы

2022-10-19 18:22 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/user/service/UserValidator.java
> +        if (name.isBlank()) {
Как я написал Выше, надо поправить на Objects.isBlank (проверьте другие места тоже)

2022-10-20 20:08 UTC, Frilock approved these changes
Принято, но NPE лучше не ловить.

2022-10-20 20:08 UTC, Frilock commented on ewm-server/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +            } catch (NullPointerException e) {
Зачем ловить NPE?) Лучше его не допускать...

2022-10-21 22:46 UTC, merged